query GetCharacters($first: Int!, $after: String) {
    allPeople(first: $first, after: $after) {
      edges {
        node {
          ...PersonItem
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }